spring:
  application:
    name: questao
  data:
    mongodb:
      uri: ${CONEXAO_MONGO_ATLAS:mongodb+srv://professor:coxinha123@app-matematica.5bpla.mongodb.net/}
      database: app-ensino-matematica-backend-questao

app:
  base-url: ${BASE_URL:http://localhost:8083}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    server-url: ${BASE_URL:http://localhost:8083} 
  show-actuator: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:https://app-matematica-eureka-f69602e28e4d.herokuapp.com/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: app-matematica-backend-questao-3a364d6ca0e2.herokuapp.com
    non-secure-port: 80
    secure-port: 443
    prefer-ip-address: false

server:
  port: ${PORT:8083}
