# spring.application.name=app_ensino_matematica_backend_questao
spring:
  data:
    mongodb:
      uri: mongodb+srv://professor:coxinha123@app-matematica.5bpla.mongodb.net/
      database: app-ensino-matematica-backend-questao
app:
  base-url: ${BASE_URL:https://app-matematica-questao-me-7fb5fa8a60ff.herokuapp.com}